### PR TITLE
March 7 Alabama

### PR DESCRIPTION
**Pull request by apgordon**
Added the March 7 shooting to your csv file.

### CODE REVIEW

**Comment by DataJenius** [comment]
Thank you so much for contributing. Unfortunately the format doesn't match- this CSV should end with the HTML from the wiki entry. All other fields are created by the R script.

**Comment by apgordon** [comment]
Ah, didn't see your R scraper file. So, how does that file kick off to begin importing the wikipedia data for cleanup? Just manually? I haven't used R before.

**Comment by DataJenius** [comment]
I wrote an ugly scraper in PHP to grab the data. I didn't share it because its built into a lot of custom MySQL dependencies I wrote for optimizing data collection. 

I will toss together something asap so anyone can scrape the wiki into a CSV directly.

**Comment by apgordon** [comment]
Cool. What kind of stuff are you trying to do in R?

For context, this morning I was noticing / surprised that someone like Washington Post doesn't already have a repo with this stuff. Stumbled onto yours and it felt like a worthy cause to try to get that data into a nice clear .csv that anyone can snag for whatever. https://twitter.com/apgordon/status/971811611605336064

**Comment by DataJenius** [comment]
I will update the ReadMe with a link to the article as soon as my partner Pouria finishes fact checking me. I'm Josh Pause (aka PineappleStreet). 

What we did was look at moving averages of incidents, and try to look at trends of violence. We also looked at the correlation between Giffords gun grade scores (ratings of state gun control efforts) to the homicide rate, school shootings and injuries in each state. 

The results were complicated... best to be cautious and finish fact checking before I say more. 

Sadly, today's attack renders everything moot, so I will need to re run this analysis anyway. I don't expect this incident will overwhelm existing trends, but let's be 100% sure before I keep blabbing. 

This is a 100% non-profit effort and I am pleased to collaborate with anyone and everyone interested in studying this issue objectively.

**Comment by DataJenius** [comment]
CK (another contributor to the project) has just informed me it is possible to use powershell to update the data in this repo every day automatically. Will implement asap.

**Comment by apgordon** [comment]
re: Giffords gun grade scores -- that's interesting. Never heard of that, but I like that train of thought. See if you there are existing differences in "gun control" by state that you can use to evaluate (at least) correlation of these events. 

re: complicated -- yeah, very. I'm no expert, just can't believe the pace we're on and wanted to at a minimum make sure the data was super easy for anyone to quickly get their hands on.

re: ReadMe -- perfect, happy to help copyedit that. 

re: scraping on some sort of scheduled job -- yeah, that'd be awesome/ideal. (what up CK)

**Comment by apgordon** [comment]
Gonna close this one out, since probably easier to just let your scrape script run and collect the data in just the right format for you R stuff.

**Comment by pineapplestreet** [comment]
Sorry for the delay- the latest data is there. Will finish automating this asap.

**Pull request closed without merging**
